export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FINISHED = 'SIGNUP_FINISHED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const PROFILE_DETAIL = 'PROFILE_DETAIL';

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';


export const BLOG_LIST = 'BLOG_LIST';
export const USER_BLOG_LIST = 'USER_BLOG_LIST';
export const BLOG_DETAIL = 'BLOG_DETAIL';
export const DELETE_BLOG = 'DELETE_BLOG';
export const DELETE_BLOG_DONE = 'DELETE_BLOG_DONE';
export const UPDATE_BLOG = 'UPDATE_BLOG';