export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FINISHED = 'SIGNUP_FINISHED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const PROFILE_DETAIL = 'PROFILE_DETAIL';


export const BLOG_LIST = 'BLOG_LIST';
export const USER_BLOG_LIST = 'USER_BLOG_LIST';