export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const PROFILE_DETAIL = 'PROFILE_DETAIL';


export const BLOG_LIST = 'BLOG_LIST';